# we create a virtual machine to execute the IR code generated by the IRGenerator. The virtual machine will have a simple instruction set and a memory model to store variables and temporary values.

class IRVM:
    def __init__(self):
        self.env={}

    def resolve(self,x):
        """
        x can be:
        - int (literal)
        - str like "a" or "t1" (variable/temp name)
        """

        if isinstance(x,int):
            return x
        
        if isinstance(x,str):
            if x not in self.env:
                raise Exception(f"Runtime error : '{x}' has no value")
            return self.env[x]
        
        raise Exception(f"runtime error: unsupported value type {type(x)}")
    

    def run(self,instructions):
        for inst in instructions:
            op=inst[0]

            if op=="STORE":
                _, name ,value=inst # unpacking the tuple 
                self.env[name]=self.resolve(value) # the resolve method is used to get the value of the variable or temporary variable. It checks if the value is an integer literal or a string representing a variable name. If it is an integer literal, it returns the integer value. If it is a string, it looks up the value in the environment dictionary (self.env) and returns it. If the variable name is not found in the environment, it raises a runtime error.
                
            elif op=="BINOP":
                _,temp,operator,left,right=inst
                l=self.resolve(left)
                r=self.resolve(right)

                if operator=="+":
                    self.env[temp]=l+r

                elif operator=="-":
                    self.env[temp]=l-r

                elif operator=="*":
                    self.env[temp]=l*r

                elif operator=="/":
                    self.env[temp]=l//r

                else:
                    raise Exception(f"runtime error: unknown error {operator}")
                

            elif op=="PRINT":
                _,value=inst
                print(self.resolve(value))

            else:
                raise Exception(f"runtime error: unknown instruction {op}")
